export const RECIPE_RETRIEVE_RECIPE_BEGIN = 'RECIPE_RETRIEVE_RECIPE_BEGIN';
export const RECIPE_RETRIEVE_RECIPE_SUCCESS = 'RECIPE_RETRIEVE_RECIPE_SUCCESS';
export const RECIPE_RETRIEVE_RECIPE_FAILURE = 'RECIPE_RETRIEVE_RECIPE_FAILURE';
export const RECIPE_RETRIEVE_RECIPE_DISMISS_ERROR = 'RECIPE_RETRIEVE_RECIPE_DISMISS_ERROR';
export const RECIPE_RETRIEVE_RECIPE_LIST_BEGIN = 'RECIPE_RETRIEVE_RECIPE_LIST_BEGIN';
export const RECIPE_RETRIEVE_RECIPE_LIST_SUCCESS = 'RECIPE_RETRIEVE_RECIPE_LIST_SUCCESS';
export const RECIPE_RETRIEVE_RECIPE_LIST_FAILURE = 'RECIPE_RETRIEVE_RECIPE_LIST_FAILURE';
export const RECIPE_RETRIEVE_RECIPE_LIST_DISMISS_ERROR = 'RECIPE_RETRIEVE_RECIPE_LIST_DISMISS_ERROR';
